name: PROD DEPLOY

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: "./.github/workflows/terraform.yml"
    with:
      aws-assume-role-arn: "arn:aws:iam::179916804929:role/github-actions-brunograna-pipeline-test"
      environment: "prod"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "brunograna-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "buildrun-terraform-state-lock"